version: '3'
services:
  animal-db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: animal_db

  animal-service:
    build: ./Dockerfile
    ports:
      - "8070:8080"
    environment:
      DB_URL: jdbc:postgresql://animal-db:5432/animal_db
    depends_on:
      - animal-db